//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbconnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderTBL()
        {
            this.OrderDetailTBL = new HashSet<OrderDetailTBL>();
        }
    
        public int SalesOrderID { get; set; }
        public Nullable<System.DateTime> SalesOrderDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public Nullable<decimal> TotalDue { get; set; }
    
        public virtual CustomerTBL CustomerTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailTBL> OrderDetailTBL { get; set; }
    }
}
