//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbconnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailTBL
    {
        public int OrderDetailID { get; set; }
        public int SalesOrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> OrderQuantity { get; set; }
    
        public virtual OrderTBL OrderTBL { get; set; }
        public virtual ProductTBL ProductTBL { get; set; }
    }
}
