//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbconnect
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTBL()
        {
            this.OrderDetailTBL = new HashSet<OrderDetailTBL>();
        }
    
        public int ProductID { get; set; }
        public string ProductDesc { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<int> QuantityInStock { get; set; }
        public Nullable<int> bin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailTBL> OrderDetailTBL { get; set; }
    }
}
